[package]
name = "wire_format"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true

clap = {version="4.5.28", features=["derive"]}
pkts = "0.2.1"
rayon.workspace = true
rscap = "0.2.2"
serde = { workspace = true, features = ["derive"] }
signal-hook.workspace = true
solana-gossip.workspace = true
solana-perf.workspace = true
solana-sanitize.workspace = true

[lints]
workspace = true
